language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker build -t udagram-reverseproxy ./project/udagram-reverseproxy
  - docker build -t udagram-frontend ./project/udagram-frontend
  
  - docker tag udagram-api-feed uvdasciylt/udagram-api-feed:v2
  - docker tag udagram-api-user uvdasciylt/udagram-api-user:v2
  - docker tag udagram-reverseproxy uvdasciylt/udagram-reverseproxy:v2
  - docker tag udagram-frontend uvdasciylt/udagram-frontend:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push uvdasciylt/udagram-api-feed:v2
  - docker push uvdasciylt/udagram-api-user:v2
  - docker push uvdasciylt/udagram-reverseproxy:v2
  - docker push uvdasciylt/udagram-frontend:v2