apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: uvdasciylt/udagram-reverseproxy:v2
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always